### ISSUE TITLE
per-disk option

### ISSUE THREAD

**Issue by felipewd** [intelsdi-x/snap-plugin-collector-disk#12]
In the metrics collected page, this plugin suggests that the metrics are per-disk.

They're indeed collected per-disk, but `snapctl metric list` only shows `/intel/procfs/disk/*/<metrics>`

So I can't collect data from only sda, for instance.

In my case, my machine has all sorts of ram[0-14], loop[0-14] which are all being collected and published.

This sounds like a minor (but important) bug to me, because in my case there's extra processing for something I'll never need and extra space/processing on the publisher side (a influx database in my case).

Talked about it on slack with @IRCody.

So please @intelsdi-x/plugin-maintainers take look and see if this can be fixed. Since I'm collecting in 1s (as suggested), this extra data scales to quite the annoyance when deployed to all my machines.

**Comment by IRCody** [comment]
Also I think this issue is related to [snap#654](https://github.com/intelsdi-x/snap/issues/654) @intelsdi-x/snap-maintainers.
