### ISSUE TITLE
Missing description of collected metrics

### ISSUE THREAD

**Issue by felipewd** [intelsdi-x/snap-plugin-collector-disk#14]
Hi,

There are a few metrics this plugin collects that aren't listed in the collected metrics section of README.

- io_time;
- weighted_io_time.

As far a I could see, these are, respectively, the 13th and 14th fields in /proc/diskstats:

https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats

> 
13 - time spent doing I/Os (ms)
14 - weighted time spent doing I/Os (ms).
>

**Comment by IRCody** [comment]
cc: @intelsdi-x/plugin-maintainers

**Comment by IzabellaRaulin** [comment]
@felipewd, thank You for pointing this. Good catch. I prepared PR (#15) which fixes that.
