### ISSUE TITLE
proc_path not presented as a "Rule"

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap-plugin-collector-disk#8]
I used this in my workflow definition:

```json
  "workflow": {
    "collect": {
      "config": {
        "/intel/procfs": {
          "proc_path": "/host-proc"
        }
      },
      "metrics": {
```

When I do `snapctl metric get -m /intel/procfs/disk/loop0/io_time` I get this:

```
$ snapctl metric get -m /intel/procfs/disk/loop0/io_time       
NAMESPACE                                VERSION         UNIT    LAST ADVERTISED TIME            DESCRIPTION
/intel/procfs/disk/loop0/io_time         3                       Fri, 17 Jun 2016 11:31:23 UTC   

  Rules for collecting /intel/procfs/disk/loop0/io_time:

       NAME      TYPE    DEFAULT         REQUIRED        MINIMUM         MAXIMUM
```

The issue is that there is no `proc_path` rule!

The "swap" plugin, for example, does not have the same issue:

```
$ snapctl metric get -m /intel/procfs/swap/io/out_pages_per_sec
NAMESPACE                                        VERSION         UNIT    LAST ADVERTISED TIME            DESCRIPTION
/intel/procfs/swap/io/out_pages_per_sec          3                       Fri, 17 Jun 2016 11:31:25 UTC   

  Rules for collecting /intel/procfs/swap/io/out_pages_per_sec:

       NAME              TYPE            DEFAULT         REQUIRED        MINIMUM         MAXIMUM
       proc_path         string          /proc           false
```

I guess this has to do with the rule [created](https://github.com/intelsdi-x/snap-plugin-collector-swap/blob/master/swap/swap.go#L271) by the "swap" plugin in the `GetConfigPolicy` function.

**Comment by tiffanyfj** [comment]
Yes, that is why. I had made a comment about the config policy rule on PR #7, but I guess it was not added.

@marcin-krolik

**Comment by marcin-krolik** [comment]
@tiffanyfj @elemoine Ineed, it's my fault. I forgot about it somehow. I will fix that.

**Comment by tiffanyfj** [comment]
No worries. Lots of comments to keep track of. Thanks @marcin-krolik !

**Comment by elemoine** [comment]
@marcin-krolik Thanks. Please coordinate with @obourdon, who might have started on that.

**Comment by obourdon** [comment]
@marcin-krolik in fact I have started working on uniformizing the way plugins get their config starting with CPU: see [one of my local commits](https://github.com/intelsdi-x/snap-plugin-collector-cpu/commit/409b63c939f6b3fbde3c3d5b7922f767bf105eb5)

**Comment by marcin-krolik** [comment]
@obourdon thanks! It looks good, go ahead with it.

**Comment by obourdon** [comment]
This issue is fixed in [this PR](https://github.com/intelsdi-x/snap-plugin-collector-disk/pull/10)

**Comment by obourdon** [comment]
@marcin-krolik @elemoine : don't know who can close this issue has the corresponding PR has been merged
